<?php

/**
 * Implements hook_ctools_plugin_directory().
 */
function nbaclubs_ctools_plugin_directory($module, $plugin)
{
    if ($module === 'entityreference') {
        return 'plugins/' . $plugin;
    }
}

/**
 * Implements hook_field_widget_form_alter().
 */
function nbaclubs_field_widget_form_alter(&$element, &$form_state, $context)
{
    // Act on our behavior.
    if (!empty($context['field']['settings']['handler_settings']['behaviors']['member_role']['status'])) {
        $items = field_get_items('node', $element['target_id']['#entity'], 'clubmember', $element['target_id']['#entity']->language);
        $element['clubmember_member_role'] = array(
            '#type'     => 'textfield',
            '#title'    => 'Club member role',
            '#weight'   => -1,
            '#required' => FALSE,
            '#default_value' => (isset($items[$element['_weight']['#default_value']]) ? $items[$element['_weight']['#default_value']]['clubmember_member_role'] : '')
        );
        $element['target_id']['#title'] = 'Club Member';
    }
}

/**
 * Implements hook_field_attach_view_alter().
 */
function nbaclubs_field_attach_view_alter(&$output, $context)
{
    // Prefix the reference with the label.
    foreach (element_children($output) as $field_name) {
        $element = &$output[$field_name];
        if ($element['#field_type'] == 'entityreference') {
            $field = field_info_field($field_name);
            if (!empty($field['settings']['handler_settings']['behaviors']['member_role']['status'])) {
                foreach ($element['#items'] as $delta => $item) {
                    $element[$delta]['#prefix'] = "<strong>{$item['clubmember_member_role']}:</strong> ";
                }
            }
        }
    }
}

/**
 * Exposed form alter
 * 
 * @param array $form
 * @param array $form_state
 * 
 * @return void
 */
function nbaclubs_form_views_exposed_form_alter(&$form, &$form_state)
{
    //Got the Form Id by using inspect element/Firebug
    if($form["#id"] == 'views-exposed-form-clubs-page') {
        $form['#attributes'] = array(
            'class' => array(
                'webform-client-form'
            )
        );
        $form['juniors']['#options'][1] = 'Yes';
        $form['coaching']['#options'][1] = 'Yes';
        
        
        $form['clubvenue']['#attributes'] = $form['clubmarked']['#attributes'] = array(
            'class' => array(
                'webform-component-select'
            )
        );
        
        $venues = array('' => 'Any');
        $nodes = node_load_multiple(array(), array('type' => 'nbaclubvenue')); 
        foreach($nodes as $venue) {
            $venues[$venue->nid] = $venue->title;
        }
        asort($venues);
        if (count($venues) > 0) {
            $form['clubvenue']['#type'] = 'select';
            unset($form['clubvenue']['#size']);
            $form['clubvenue']['#multiple'] = false;
            $form['clubvenue']['#options'] = $venues;
        } else {
            unset($form['clubvenue']);
        }
    }
}

/**
 * Attach a map to the club node if the long / lat are present
 *
 * @return void
 */
function nbaclubs_node_view($node, $view_mode, $lang_code)
{
    if ($node && $node->type == 'nbaclubvenue') {
        if (function_exists('leafletmaputils_attach_scripts')) {
            $lat = nbaclubs_get_field_value($node, 'venue_lat');
            $long = nbaclubs_get_field_value($node, 'venue_long');
            $address = nbaclubs_get_field_value($node, 'venue_address');
            if (drupal_strlen($address) > 0) {
                $address = '<address>' . $address . '</address>';
            }
            
            if (drupal_strlen($lat) > 0 && drupal_strlen($long) > 0) {
                leafletmaputils_attach_scripts($node->content);
                $node->content['#attached']['js'][] = array(
                    'data' => array(
                        'nbaclubvenue' => array(
                            array(
                                'lat' => floatval($lat),
                                'lng' => floatval($long)
                            )
                        )
                    ),
                    'type' => 'setting'
                );
                $node->content['#attached']['js'][drupal_get_path('module', 'nbaclubs') . '/js/venueMap.js'] = array(
                    'weight' => 1,
                    'scope' => 'footer',
                    'defer' => true
                );
                
                $node->content['map'] = array(
                    '#markup' => '<div class="card">'
                    . '<div style="height: 400px;" class="card_content nbaclubvenue_map" id="nbaclubvenue_map"></div>'
                    . '<div class="card_content nbaclubvenue_map_title">' . $node->title . $address . '</div>'
                    . '</div>',
                    '#weight' => 10
                );
                unset($node->content['venue_address']);
            }
        }
        
        if ($view_mode == 'teaser') {
            unset($node->content['body']);
            $node->content['title'] = array(
                '#markup' => $node->title
            );
        }

        unset($node->content['venue_long']);
        unset($node->content['venue_lat']);
    }
    
    if ($node && $node->type == 'nbaclub' && $view_mode == 'full') {
        if (isset($node->content['clubvenue'])) {
            $node->content['clubvenue']['#prefix'] = t(
                '<h3 class="c-title c-title-medium">@title</h3>',
                array(
                    '@title' => 'This club plays at: '
                )
            );
        }
    } else if ($node && $node->type == 'nbaclub' && $view_mode == 'teaser') {
        unset($node->content['clubvenue']);
    }
    
    if ($node && $node->type == 'nbaclub') {
        $meta = array();
        $venues = array();
        foreach (entity_metadata_wrapper('node', $node->nid)->clubvenue->value() as $venue) {
            $venues[$venue->nid] = $venue->title;
        }
        
        if (count($venues) > 0) {
            $meta['venues'] = $venues;
        }
        
        foreach (array('juniors', 'clubmarked', 'coaching') as $type) {
            if (isset(entity_metadata_wrapper('node', $node->nid)->$type) 
                && entity_metadata_wrapper('node', $node->nid)->$type->value()
            ) {
                $meta[$type] = entity_metadata_wrapper('node', $node->nid)->$type->value();
            }
        }
        
        $node->meta = $meta;
    }
}

/**
 * Get the raw value of a field
 *
 * @return string
 */
function nbaclubs_get_field_value($node, $field_name, $delta = 0)
{
    $field = field_get_items('node', $node, $field_name);
    $value = field_view_value('node', $node, $field_name, $field[$delta]);
    return render($value);
}

/**
 * Get the club marked qualifications
 * 
 * @return array
 */
function nbaclubs_get_clubmarks()
{
    return array(
        'ClubMark' => 'ClubMark',
        'Premier Club' => 'Premier Club'
    );
}